; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = sticks3

[env]
platform = espressif32@6.12.0
board = freenove_esp32_s3_wroom
framework = arduino
board_build.arduino.partitions = default_8MB.csv
board_build.memory_type = qio_opi
monitor_speed = 115200
upload_speed = 921600
build_unflags =
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_USB_MODE=0
build_flags =
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_ldf_mode = chain+
lib_deps =
  https://github.com/m5stack/M5GFX.git#0.2.25
  m5stack/M5Unified@0.2.18
  knolleary/PubSubClient@2.8

[env:sticks3]
build_flags =
  ${env.build_flags}
  -DECHOLINK_TRANSPORT_HYBRID
